matrix:
  include:
    - os: osx
      osx_image: xcode11.5
      language: node_js
      node_js: '12'

    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

script:
  - echo "$CSC_KEY_PASSWORD" > csc_key_pass.txt
  - gpg --batch --yes --passphrase $GPG_PASS -c csc_key_pass.txt
  - cat csc_key_pass.txt.gpg | base64 -
  - echo "$CSC_LINK" > csc_link.txt
  - gpg --batch --yes --passphrase $GPG_PASS -c csc_link.txt
  - cat csc_link.txt.gpg | base64 -

branches:
  only:
  - master
