name: Build Releases

on:
  push:
    branches:
      - "master"

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: sudo apt-get install libx11-dev zlib1g-dev libpng-dev libxtst-dev

      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ github.token }}

  build-windows:
    name: Build Windows
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ github.token }}

  build-mac:
    name: Build Mac
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.5'

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: '${{ runner.os }}-nodemodules-${{ hashFiles(''package-lock.json'') }}'
          restore-keys: "${{ runner.os }}-nodemodules-"

      - run: npm install

      - run: npm run dist
        env:
          GH_TOKEN: ${{ github.token }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD : ${{ secrets.CSC_KEY_PASSWORD  }}
